### ISSUE TITLE
feat: Add my data

### ISSUE THREAD

**Issue by RoshanMhatre** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#170]
I want to add my data to this repository.
Please assign this issue to me and add the Hacktoberfest label to this issue.

**Comment by CodingSpecies** [comment]
@RoshanMhatre sure, when you make the pull request, then I will add the hacktoberfest accepted label.  If you need any help feel free to reopen this.

**Comment by RoshanMhatre** [comment]
Can you add the Hacktoberfest label to this issue?
For PR, you can do it after I launch the PR, but for the issue to be taken into consideration for the hacktoberfest, it needs to have a label for it.

**Comment by CodingSpecies** [comment]
@RoshanMhatre I am not sure if I am meant to do this, as it is only meant to be the pull request, perhaps let's see what @iamdevvalecha says. Thank you.

**Comment by RoshanMhatre** [comment]
Thank you @CodingSpecies!
