### ISSUE TITLE
[EXAMPLE ISSUE] How to create first pull request

### ISSUE THREAD

**Issue by iamdevvalecha** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#2]
## What to do:
> **➡ This is an example issue, explaining what you need to do ⬅**

### 1. Add your profile picture to the folder:
Add a picture picture of your choice in **static/images/.**  Accepted files are *png* and *jpg*, should be **squared** and minimum size `544x544` pixels. Ex.

`static/images/<YOUR-USERNAME>.png`

### 2. Add your profile information
Create a markdown file in your folder following the convention `content/participant/<YOUR-USERNAME>.md.` Ex.

`content/participant/<YOUR-USERNAME>.md/`

### Copy the next template into your file, delete the boilerplate data and fill the information with yours.

`name: YOURNAME
institution/company: INSTITUTION_NAME
github:USERNAME
`

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by iamdevvalecha** [comment]
@aniket-24 go ahead!

**Comment by iamdevvalecha** [comment]
this is a sample pr....

**Comment by aniket-24** [comment]
Can you assign me this issue? @iamdevvalecha  @coderaj05

**Comment by aniket-24** [comment]
> @aniket-24 I think this is an issue, that is used as an example, as it explains what you have to do, so I don't think you can be assigned to this, as there is nothing to do. Thanks.

okay!

**Comment by Ayan-thecodeking** [comment]
Hey pls assign this to me @iamdevvalecha

**Comment by himanshuchandola** [comment]
Raised PR about myself #23

**Comment by Harsh-0986** [comment]
Raised PR Please review my PR  #32

**Comment by CodingSpecies** [comment]
> 
> 
> Hey pls assign this to me @iamdevvalecha

@Ayan-thecodeking this is an example issue, it doesn't need anyone to be assigned, it just explains what to do. thanks

**Comment by avyayjain** [comment]
pls add me to this pr

**Comment by thesarthakjain** [comment]
@iamdevvalecha Please review my PR #48

**Comment by KunalJaiswal-17** [comment]
@iamdevvalecha Raised PR Please review my PR #50

**Comment by Heisenberg-737** [comment]
@iamdevvalecha Please review my PR #99

**Comment by tiwarishubham635** [comment]
Please review my Pull Request #97

**Comment by Vaibhav5702** [comment]
Please assign me this issue

**Comment by CodingSpecies** [comment]
@Vaibhav5702 this issue is an example. This means no-one can be assigned to it. If you would like, please open a pull request, adding yourself, by following the rules on the first comment for this issue. Thank you.

**Comment by utkarshluthra** [comment]
Check PR #112
Added data as per requirement

**Comment by Jatinkumar30** [comment]
Raised PR about myself #112

**Comment by Khushi-agarwal** [comment]
Raised a pr#160.

**Comment by drishyadamodaran** [comment]
Raised a PR #169
