### ISSUE TITLE
I want to add and update CONTRIBUTNG.md

### ISSUE THREAD

**Issue by prabaljainn** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#208]
**Hey, i want to add and contribute to CONTRIBUTNG.md**

_**assign this task to me_**_

**Comment by CodingSpecies** [comment]
@prabaljainn This issue is assigned to you. 
Thank you.

**Comment by prabaljainn** [comment]
Just did a PullR for a base Contributing.md file do consider it

**Comment by prabaljainn** [comment]
please add a Hacktoberfest tag to my PR and Isuue
