### ISSUE TITLE
added my self

### ISSUE THREAD

**Issue by andianiputri** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#216]
![xCXl09mm_400x400](https://user-images.githubusercontent.com/56747639/135738110-4e4757c2-6cd2-45c5-b35b-52b7dab945e8.jpg)

**Comment by CodingSpecies** [comment]
@andianiputri  what you need to do:
https://github.com/Binary-Cumates/Hacktoberfest-21-Open-First-PR/issues/2#issue-1011191529

**Comment by CodingSpecies** [comment]
If you need any help, feel free to reopen this issue. Just make a pr, with what the above link says, then hopefully, if successful get the hacktoberfest label. Thanks. @andianiputri
