### ISSUE TITLE
create a new task to project admin.

### ISSUE THREAD

**Issue by iamdevvalecha** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#235]
Task 3 to follow me @iamdevvalecha 
[![GitHub followers](https://img.shields.io/github/followers/iamdevvalecha.svg?label=Follow%20@iamdevvalecha&style=social)](https://github.com/iamdevvalecha/)

**Comment by iamdevvalecha** [comment]
@CodingSpecies can you please add in task 3 to follow project admin.

**Comment by CodingSpecies** [comment]
@iamdevvalecha I am not sure what I am meant to do, please can you elaborate? Thank you

**Comment by iamdevvalecha** [comment]
in readme.md file you have to create task 3 where people raising pull request they have to follow project admin @iamdevvalecha .

**Comment by iamdevvalecha** [comment]
@CodingSpecies status?
