### ISSUE TITLE
**Excluded Project**

### ISSUE THREAD

**Issue by gokulrajpuviyarasu** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#271]
**This repo is Excluded from the hacktoberfest please don't waste your time. But you can use it for practice**

**Comment by CodingSpecies** [comment]
@gokulrajpuviyarasu is this not part of hacktoberfest?

**Comment by CodingSpecies** [comment]
@gokulrajpuviyarasu when it was part of @iamdevvalecha repo, it seemed to work, but now when I checked my hacktoberfest, it is not part. 
How come it moved from being @iamdevvalecha 's repo, to being part of @binary-cumates ?

**Comment by nikhilbuts** [comment]
@CodingSpecies Check Some Spell Mistake If any. Also Add "Hacktoberfest" in label and refresh your Hacktoberfest profile.

Actually, I have same issue and getting Project not participating so I checked in my repo and have some spell mistakes.

**Comment by CodingSpecies** [comment]
@nikhilbuts should I simply but the hacktoberfest label in all the prs?

**Comment by CodingSpecies** [comment]
@nikhilbuts @gokulrajpuviyarasu this is because of this:
![image](https://user-images.githubusercontent.com/70807500/135768510-583c8e75-ff78-4f8a-a993-b28fb4bb79b6.png)
someone else had shared this on a repo, also explaining that repos that are solely made for pull requests, will not count.

**Comment by gokulrajpuviyarasu** [comment]
> @gokulrajpuviyarasu when it was part of @iamdevvalecha repo, it seemed to work, but now when I checked my hacktoberfest, it is not part. How come it moved from being @iamdevvalecha 's repo, to being part of @Binary-Cumates ?

**Maybe Now his repo also have the same issue**
