### ISSUE TITLE
Project is excluded from Hacktoberfest 2021?

### ISSUE THREAD

**Issue by HaylzRandom** [Binary-Cumates/Hacktoberfest-21-Open-First-PR#284]
Even though my PR had the appropriate tag, it has flagged up as being excluded?

![image](https://user-images.githubusercontent.com/15155380/135838604-4a1f10e2-3553-4e48-99f9-8069d048ca99.png)

**Comment by iamdevvalecha** [comment]
@HaylzRandom yes now it's a practice project
